//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_ASP.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet_ASP.Resources.Models.ApplicationUser", typeof(ApplicationUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string adresse {
            get {
                return ResourceManager.GetString("adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string adresseReq {
            get {
                return ResourceManager.GetString("adresseReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordReq {
            get {
                return ResourceManager.GetString("ConfirmPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil image.
        /// </summary>
        public static string imageBytes {
            get {
                return ResourceManager.GetString("imageBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupant.
        /// </summary>
        public static string locataire {
            get {
                return ResourceManager.GetString("locataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        public static string no_acc {
            get {
                return ResourceManager.GetString("no_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string nomComplet {
            get {
                return ResourceManager.GetString("nomComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name est obligatoire.
        /// </summary>
        public static string nomCompletReq {
            get {
                return ResourceManager.GetString("nomCompletReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long..
        /// </summary>
        public static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil type.
        /// </summary>
        public static string profileType {
            get {
                return ResourceManager.GetString("profileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil type is required.
        /// </summary>
        public static string profileTypeReq {
            get {
                return ResourceManager.GetString("profileTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string proprietaire {
            get {
                return ResourceManager.GetString("proprietaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        public static string telReq {
            get {
                return ResourceManager.GetString("telReq", resourceCulture);
            }
        }
    }
}
