//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_ASP.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reservation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reservation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet_ASP.Resources.Models.Reservation", typeof(Reservation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string cout {
            get {
                return ResourceManager.GetString("cout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost is required.
        /// </summary>
        public static string coutReq {
            get {
                return ResourceManager.GetString("coutReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string dateDebut {
            get {
                return ResourceManager.GetString("dateDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string dateDebutReq {
            get {
                return ResourceManager.GetString("dateDebutReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string dateFin {
            get {
                return ResourceManager.GetString("dateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required.
        /// </summary>
        public static string dateFinReq {
            get {
                return ResourceManager.GetString("dateFinReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        public static string dateReservation {
            get {
                return ResourceManager.GetString("dateReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date is required.
        /// </summary>
        public static string dateReservationReq {
            get {
                return ResourceManager.GetString("dateReservationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Returned?.
        /// </summary>
        public static string doesCarReturned {
            get {
                return ResourceManager.GetString("doesCarReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupant.
        /// </summary>
        public static string locataire {
            get {
                return ResourceManager.GetString("locataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        public static string totalCost {
            get {
                return ResourceManager.GetString("totalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total days.
        /// </summary>
        public static string totaldays {
            get {
                return ResourceManager.GetString("totaldays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paiement type.
        /// </summary>
        public static string typeDePaiement {
            get {
                return ResourceManager.GetString("typeDePaiement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paiement type is required.
        /// </summary>
        public static string typeDePaiementReq {
            get {
                return ResourceManager.GetString("typeDePaiementReq", resourceCulture);
            }
        }
    }
}
