//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_ASP.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Voitures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voitures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet_ASP.Resources.Models.Voitures", typeof(Voitures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string automatique {
            get {
                return ResourceManager.GetString("automatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string couleur {
            get {
                return ResourceManager.GetString("couleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is required.
        /// </summary>
        public static string couleurReq {
            get {
                return ResourceManager.GetString("couleurReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per day.
        /// </summary>
        public static string coutParJour {
            get {
                return ResourceManager.GetString("coutParJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per dayis required.
        /// </summary>
        public static string coutParJourReq {
            get {
                return ResourceManager.GetString("coutParJourReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibility.
        /// </summary>
        public static string disponible {
            get {
                return ResourceManager.GetString("disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string marque {
            get {
                return ResourceManager.GetString("marque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark is required.
        /// </summary>
        public static string marqueReq {
            get {
                return ResourceManager.GetString("marqueReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration number.
        /// </summary>
        public static string matricule {
            get {
                return ResourceManager.GetString("matricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration number is required.
        /// </summary>
        public static string matriculeReq {
            get {
                return ResourceManager.GetString("matriculeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is required.
        /// </summary>
        public static string modelReq {
            get {
                return ResourceManager.GetString("modelReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats.
        /// </summary>
        public static string nbPlaces {
            get {
                return ResourceManager.GetString("nbPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seats is required.
        /// </summary>
        public static string nbPlacesReq {
            get {
                return ResourceManager.GetString("nbPlacesReq", resourceCulture);
            }
        }
    }
}
