// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updated_car_model_removed_km : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_car_model_removed_km));
        
        string IMigrationMetadata.Id
        {
            get { return "202102022055443_updated_car_model_removed_km"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
