// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class listNoire_shared_btwn_admins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listNoire_shared_btwn_admins));
        
        string IMigrationMetadata.Id
        {
            get { return "202102161320230_listNoire_shared_btwn_admins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
