// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modified_app_user_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modified_app_user_class));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301634063_modified_app_user_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
