// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updated_models_attribus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_models_attribus));
        
        string IMigrationMetadata.Id
        {
            get { return "202102011257367_updated_models_attribus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
