// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class car_model_to_coutparjr_as_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(car_model_to_coutparjr_as_string));
        
        string IMigrationMetadata.Id
        {
            get { return "202102032003106_car_model_to_coutparjr_as_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
