// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_img_to_appUser_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_img_to_appUser_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031222555_add_img_to_appUser_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
