// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updated_car_model_img_bytes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_car_model_img_bytes));
        
        string IMigrationMetadata.Id
        {
            get { return "202102030157129_updated_car_model_img_bytes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
