// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Ressource_dir_for_internationalisation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Ressource_dir_for_internationalisation));
        
        string IMigrationMetadata.Id
        {
            get { return "202102102355097_added_Ressource_dir_for_internationalisation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
