// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_appUser_to_myusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_appUser_to_myusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301539297_added_appUser_to_myusers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
