// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editited_voiture_tab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editited_voiture_tab));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301950071_editited_voiture_tab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
