// <auto-generated />
namespace projet_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reservations_fk_accessibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reservations_fk_accessibility));
        
        string IMigrationMetadata.Id
        {
            get { return "202102062228210_reservations_fk_accessibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
